config/routes.rb
Rails.application.routes.draw do
  #get 'rooms/index'
  
  #get 'home/index'

  resources :rooms do 
    resources :messages
  end
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room, optional: true
  validates :room, presence:true
  validates :body, :username, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  
  validates :name, presence: true, uniqueness:true

  has_many :messages, dependent: :destroy, inverse_of: :room

  accepts_nested_attributes_for :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 

  helper_method :current_user

  def current_user
    session[:username]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @rooms = Room.all 
    @room = Room.new
    @room.messages.build
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    set_room
    @messages = @room.messages

    respond_to do |format|
      format.html 
      format.js
      format.json { render(json: @messages) }
    end    #render(layout: false)
  end

  def create
    # POST /room/show.html.erb
    set_room
    #@message = Message.new(message_params.merge(room_id: @room.id)) same
    @message = @room.messages.build(message_params)
    if @message.save
      unless current_user
        session[:username] = @message.username
      end       #redirect_to(@room)
    end
    #else
      #flash[:error] = "Error:#{@message.errors.full_messages.to_sentence}"
      #redirect_to(room_path(@room))
    #end
    respond_to do |format|
      format.html do 
        if @message.persisted?
          redirect_to(@room)
        else
          flash[:error] = "Error:#{@room.errors.full_messages.to_sentence}"
          redirect_to(room_path)
        end
      end
      format.js
    end
  end

  private
    def set_room
      @room = Room.find(params[:room_id])
    end

    def message_params
      params.require(:message).permit(:body, :username)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room = Room.new
    @rooms = Room.all.order('created_at DESC')
    
  end
  
  def show
    @room = Room.find(params[:id])
    @messages = @room.messages
  end

  def create 
    @room = Room.new(room_params)
    if @room.save
      # Create message if needed
      #if params[:room][:message]
        #@room.messages.build(username: params[:room[:message][:username]])
      if message = @room.messages.first
        session[:username] = message.username
      end
      flash[:success] = "erro: Room was saved successfully."
      redirect_to(room_path(@room))
    else
      flash[:error] = "Error: #{@room.errors.full_messages.to_sentence}"
      redirect_to(root_path)
    end
  end

  private 
    def room_params 
      params.require(:room).permit(:name, messages_attributes:[:username, :body])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts={})
    flash.map do |key, message|
      content_tag(:div,message,class:"alert #{bootstrap_class_for(key)} show") do
      content_tag(:button,'x'.html_safe,class:'close',data: {dismiss: 'alert'}) + message 
      end
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1><strong>Welcome</strong></h1>
  <p>Choose your room</p>

  <ol>
    <% @rooms.each do |room| %>
      <li><%= link_to(room.name, room_path(room)) %> 
      <span class="badge badge-primary"><%= room.messages.count %></span>
    </li>
    <% end %>
  </ol>
</div>
<%= form_for(@room) do |f| %>
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <%# <div class="panel-heading"></div> %>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label(:name) %>
          <%= f.text_field(:name, class: 'form-control') %>
        </div>   
            
      </div> 
 <%#    </div>    %>   
<%#   </div>  
  <div class="col-md-8 col-md-offset-2"> %>
    <div class="panel panel-default">
      <%# <div class="panel-heading"></div> %>
      <div class="panel-body"> 
        <div class="form-group">
          <p>  Username and first message</p>
          <%= f.fields_for(:messages) do |field| %>
            <%= field.text_field(:username, class: 'form-control', placeholder: "Username") %>
             <%= field.text_field(:body, class: 'form-control', placeholder: "Your Message") %>
          <% end %>
        </div>
         <%= f.submit(nil, class: 'btn btn-primary form-control') %> 
      </div>
     </div>
     </div>
   </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Room", root_path, class: "navbar-brand" ) %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"></ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Home", root_path) %></li>
        <li><%= link_to("About Us", '#') %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" >
  </head>

  <body>
    <%= render('layouts/navigation') %>
    <div class="container">
      <%= flash_messages %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/messages/_message.html.erb
<div class="list-group-item">
  <div class="badge badge-primary"><%= message.username %></div>
  <span><%= message.body %></span>         
</div>

app/views/messages/create.js.erb
 <%# var appendItem = {
   init: function(){
     $(".messages").append("<%= j render(@message) >");
     $("input#message_body").val("");
   }
 }

 appendItem.init();
  %>
var Create = {
  init: function(){
    var messages     = document.querySelector(".messages");
    var message_body = document.querySelector("input#message_body");
    messages.innerHTML += "<%= j render(@message) %>";
    message_body.value = "";
  },
  reloadJSON: function(){
    $.getJSON("<%= room_messages_path(@room, format: :json) %>", function(responseText){
      console.log("ResponseText ", responseText);
    });
  },

  success: function(){
    console.log("Create done updating.."); 
  }
}

Create.init();
Create.success();
Create.reloadJSON();

app/views/messages/index.html.erb
<%= render(@messages) %>

app/views/messages/index.js.erb
$(".messages").html("<%= j render(@messages) %>");
console.log("done updating..");

app/views/rooms/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Welcome</h1>
  <p>Choose your room</p>

</div>
<%= form_for(Room.new) do |f| %>
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading"></div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label(:name) %>
          <%= f.text_field(:name, class: 'form-control') %>
        </div>   
          <%= f.submit(nil, class: 'btn btn-primary form-control') %>    
      </div> 
    </div>      
  </div>  
<% end %>

app/views/rooms/show.html.erb
<div class="col-md-8 col-md-offset-2 messages">
  <h1>Room: <%= @room.name %></h1>

  <div class="list-group mb-3">
    <%# @messages.each do |message|%>
      <%# render(@messages) %>
    <%# end %>
    <%= render(@messages) %>
  </div>
</div>
<div class="col-md-8 col-md-offset-2">

  <div class="panel panel-default room-color">
      <div class="panel-body">
        <%# <form action="/room/123/messages" method="post"></form> %>

        <%# <%= form_for(room_messages_path)  same as ..%>
        <%# <%= form_for(@room, url: room_messages_path)  same as ..%> 
        <%# <%= form_for([@room, @message=Message.new(username: current_user)] %>
        <%= form_for([@room, @message=Message.new(username: current_user)],remote: true) do |f|%> 
          <p>Iam not crazy right</p>
          <div class="d-flex align-items-stretch">
            <%= f.label(:body) %>
            <%= f.text_field(:body, class:'mr-1', placeholder: "Type your message") %>
            <%= f.label(:username) %>
            <%= f.text_field(:username, class:'mr-1', placeholder: "username", required: true) %>
          <%= f.submit(nil, class: 'btn btn-primary') %> 
          </div>  
        <% end %>
      </div>
  </div>
  
</div>

<script type="text/javascript" charset="utf-7">
  function reload(){
    $.get("<%= room_messages_path(@room, format: :js) %>", function(response){
            //console.log("Run successfully ", response);
      });  
  }
  setInterval(reload,3000);
</script>